### PR TITLE
Perfomance optimization, two new scramblers, implement quadtree

### PR DESCRIPTION
**Pull request by Luka967**
Todo:
- fix players' cells disappearing from view when out of borders
- enhance perfomance by a lot by not binding food nodes to NodeHandler

### CODE REVIEW

**Comment by ZfsrGhS953** [comment]
A quadtree that's not copyrighted... Something I wanted to happen and now it's done!

**Comment by NatsuTheGreat** [comment]
Did you read through what he said completely? -.-

**Comment by ZfsrGhS953** [comment]
I downvoted him and gave an upvote, a smile, an ice cream, and a heart to luka967.

**Comment by NatsuTheGreat** [comment]
....

**Comment by Barbosik** [comment]
@NatsuTheGreat: This guy ZfsrGhS953 is a minion service owner and as I know he also owner of petridish. He distributed MultiOgar source code with removed copyright header. And claimed that it's his code. He using renamed MultiOgar servers. 

I helped him with a new protocol, but now he angry at me, because I didn't helped him to revive his minion service.

**Comment by NatsuTheGreat** [comment]
Didn't know the owner of petridish can be such a person. I thought the owner would be better.

**Comment by Barbosik** [comment]
I too

**Comment by NatsuTheGreat** [comment]
>but now he angry at me, because I didn't helped him to revive his minion service.

This type of behavior from an over of a site that gets thousands of players? Just really...

**Comment by Barbosik** [comment]
@Luka967: "almost"?

yes, you copied almost all physics behavior from MultiOgar.

Regarding to QuadNode, you make the following changes to QuadNode.js:
1) QuadNode renamed to QuadTree
2) this.bound renamed to this.range
3) function "insert" renamed to "add"
4) etc

For example, let's compare function "remove":

Original code: https://github.com/Barbosik/QuadNode/blob/master/QuadNode.js#L101-L113
```
QuadNode.prototype.remove = function (item) {
    if (item._quadNode != this) {
        item._quadNode.remove(item);
        return;
    }
    var index = this.items.indexOf(item);
    if (index < 0) {
        throw new TypeError("QuadNode.remove: item not found!");
    }
    this.items.splice(index, 1);
    item._quadNode = null;
    cleanup(this);
};
```
Your modification: https://github.com/OgarProject/Ogar/blob/master/src/modules/QuadTree.js#L44-L60
```
QuadTree.prototype.remove = function(item, merge) {
// === PART ADDED BY LUKA967=== 
    if (!item) return;
    if (merge == null || merge == undefined) merge = true;

    if (item instanceof Array) {
        // handle arrays
        for (var i = 0; i < item.length; i++) this.add(item[i], merge);
    } else {
        if (!item.__quad) return;
// === END OF PART ADDED BY LUKA967=== 

        var index = item.__quad.nodes.indexOf(item);
        if (index != -1) item.__quad.nodes.splice(index, 1);

        if (merge) item.__quad.merge();
        item.__quad = null;
    }
};
```

Let's compare it more detail:

Original fragment:
```
    var index = this.items.indexOf(item);
    if (index < 0) {
        throw new TypeError("QuadNode.remove: item not found!");
    }
    this.items.splice(index, 1);
    item._quadNode = null;
    cleanup(this);
```

Luka967 fragment:
```
        var index = item.__quad.nodes.indexOf(item);
        if (index != -1) item.__quad.nodes.splice(index, 1);

        if (merge) item.__quad.merge();
        item.__quad = null;
```

The judge will not listen to your words, he will just appoint technical expertise which will be made by technical expert. And your modifications will not help you to hide original code.

And you talking that there is no difference? :smile:

**Comment by IAP-Reloaded** [comment]
@Barbosik I can't believe they stole your code... 😦

**Comment by Barbosik** [comment]
@IAP-Reloaded: actually he copied almost all physics from MultiOgar :) 
I don't know the reason why he decided to violate U.S. Copyright laws and to show disrespect to authors which help him with code. Probably he is just younger and don't understand that after such behavior, no one will not deal with him.

**Comment by Luka967** [comment]
@Barbosik 
If you're actually that sure the infringing file is a copy of the source file, go ahead, make a move.
I'm just writing some unnecessary stuff here.

1.
> actually he copied almost all physics from MultiOgar :)

Incorrect.
Compare this:
```js
CollisionHandler.prototype.pushApart = function(cell, check) {
    if (cell.nodeId == check.nodeId) return; // Can't collide with self

    var cartesian = cell.position.clone().sub(check.position);

    var dist = cartesian.distance();
    var angle = cartesian.angle();
    var maxDist = cell.getSize() + check.getSize();

    if (dist < maxDist) {
        // Push cell apart
        var mult = Math.sqrt(check.mass / cell.mass) / 2;
        var outward = (maxDist - dist) * mult;

        // Resolve jittering
        outward = Math.min(outward, maxDist - dist);

        cell.position.add(
            Math.sin(angle) * outward,
            Math.cos(angle) * outward
        );
        return true;
    } else return false;
};
```
with this:
```js
GameServer.prototype.resolveRigidCollision = function (manifold, border) {
    // distance from cell1 to cell2
    var d = Math.sqrt(manifold.squared);
    if (d <= 0) return;
    var invd = 1 / d;
    
    // normal
    var nx = manifold.dx * invd;
    var ny = manifold.dy * invd;
    
    // body penetration distance
    var penetration = manifold.r - d;
    if (penetration <= 0) return;
    
    // penetration vector = penetration * normal
    var px = penetration * nx;
    var py = penetration * ny;
    
    // body impulse
    var totalMass = manifold.cell1.getSizeSquared() + manifold.cell2.getSizeSquared();
    if (totalMass <= 0) return;
    var invTotalMass = 1 / totalMass;
    var impulse1 = manifold.cell2.getSizeSquared() * invTotalMass;
    var impulse2 = manifold.cell1.getSizeSquared() * invTotalMass;
    
    // apply extrusion force
    manifold.cell1.position.x -= px * impulse1;
    manifold.cell1.position.y -= py * impulse1;
    manifold.cell2.position.x += px * impulse2;
    manifold.cell2.position.y += py * impulse2;
    // clip to border bounds
    manifold.cell1.checkBorder(border);
    manifold.cell2.checkBorder(border);
};
```
I see very little amount of text that is identical to these two parts of code.
2. [This link which leads to streamable.com](https://streamable.com/fdd9) still confirms that I, the author of the "infringing" file on [Github](https://github.com/OgarProject/Ogar/blob/master/src/modules/QuadTree.js) modified a large portion of this file and means that the ["author"](https://github.com/Barbosik) stating the code has been copied and modified with violation of [this Apache license](https://github.com/Barbosik/QuadNode/blob/master/LICENSE) is telling falsehood.

**Comment by Barbosik** [comment]
@Luka967: _Compare this:_

Luka967, please don't think that other people is so stupid and you can deceive them with renaming variables and code mixing. I reviewed your change and can see pretty clear that it copies almost full approach and includes a lot of clean copy-paste. I understand your very well and don't want to deal with you anymore. Good luck

**Comment by ZfsrGhS953** [comment]
Also, I remember something when I discovered MultiOgar. When you said you will make a even faster version of multiogar, I said "Don't, rewrite it in assembly instead." And you deleted it. I think there was a misunderstanding, I meant to say something like "If you know assembly, don't miss the opportunity to make it the fastest, even if it will take you longer." I think you understood me as if I wanted you to write multiogar in a language you don't know.

**Comment by Barbosik** [comment]
@ZfsrGhS953: I don't need to rewrite it in another language. I already have server and client written in C#. It works faster, but my interest in MultiOgar is to learn node.js capabilities. It means that I'm interested to implement faster server in plain javascript. To look how JS works in comparison with other languages. And at a glance JS works pretty well, almost fast as C#.

**Comment by ZfsrGhS953** [comment]
You also said that I added some mistaken code that can't improve performance. Well then look at this function that can fire thousands of times per tick when the split limit is high:
`
// Resolves rigid body collision
GameServer.prototype.resolveRigidCollision = function (manifold, border) {
    // distance from cell1 to cell2
    var d = Math.sqrt(manifold.squared);
    if (d <= 0) return;
	
    // body penetration distance
    var penetration = (manifold.r - d)/d;
    
    // penetration vector = penetration * normal
    var px = penetration * manifold.dx;
    var py = penetration * manifold.dy;
    
    // body impulse
    var totalMass = manifold.cell1._mass + manifold.cell2._mass;
    var impulse1 = manifold.cell2._mass / totalMass;
    var impulse2 = manifold.cell1._mass / totalMass;
    
    // apply extrusion force
    manifold.cell1.position.x -= px * impulse1;
    manifold.cell1.position.y -= py * impulse1;
    manifold.cell2.position.x += px * impulse2;
    manifold.cell2.position.y += py * impulse2;
};
`
So, how this improves performance? So, first of all, it doesn't check if the total mass is negative. It's not needed unless you're debugging, so I removed it. But I agree that it should be commented, not removed. Next is removal of "invTotalMass". Why? The previous code had 4 variable declares, 1 addition, 1 division and 2 multiplication. Let's ignore those that were not changed in my code. That's 1 variable declare ("invTotalMass"), 1 division(1/d) and 2 multiplications (*totalMass), In my code there are NO variable declares and multiplications, and 2 divisions(/totalMass). Even if I assume that variable declare doesn't take any CPU time, 1 extra division is still about 70% faster than 2 multiplications, despite that divisions take more time than multiplications.

**Comment by Barbosik** [comment]
1) So, first of all, it doesn't check if the total mass is negative. It's not needed unless you're debugging, so I removed it.

You will not take you any performance gain with this, vice versa you will get hidden bug by remove check if the mass will be zero (for example some bug in the code).
And you're trying to "optimize" code which already works very fast and has no issues with performance. May be it will be news for you, but this code doesn't works thousands of times per tick :smile:
Even if you remove this function at all you will not get significant performance improvement

**Comment by NatsuTheGreat** [comment]
@Barbosik >But his hate doesn't matter for me.

That's good :)

@ZfsrGhS953 >Well then look at this function that can fire thousands of times per tick when the split limit is high

How does that make it better? You are only going to get high extreme lag if a function is called thousand of times per tick...

@ZfsrGhS953 >In my code there are NO variable declares and multiplications

I don't know what these are then:

```
    // body penetration distance
    var penetration = (manifold.r - d)/d;

    // penetration vector = penetration * normal
    var px = penetration * manifold.dx;
    var py = penetration * manifold.dy;
```

**Comment by Barbosik** [comment]
@ZfsrGhS953: In my code there are NO variable declares and multiplications

1) do you know that variable declaration doesn't consume cpu time?

2) do you know that multiplication is more easy and faster operation than divide (which you added)?

**Comment by NatsuTheGreat** [comment]
@Barbosik He is saying that multiplication is so much slower that he didn't even care to change the following:

```
    // penetration vector = penetration * normal
    var px = penetration * manifold.dx;
    var py = penetration * manifold.dy;


    // apply extrusion force
    manifold.cell1.position.x -= px * impulse1;
    manifold.cell1.position.y -= py * impulse1;
    manifold.cell2.position.x += px * impulse2;
    manifold.cell2.position.y += py * impulse2;
```

**Comment by Barbosik** [comment]
@NatsuTheGreat: he trying to "optimize" code which already works as fast, has no any issue with performace and cannot affect performance significantly.

**Comment by NatsuTheGreat** [comment]
@ZfsrGhS953 By changing your code to division, you made it slower. But here, you are worrying about micro level optimizations. Your code does not speed it up. Multiplication does have faster performance than division, but it's so little, that you only need to worry about it if you are declaring massive amounts of math-related variables. All you did was change up variable names and slow down your code (only by a little though) so truly the only difference was variable name changes. You could even have worse collision now.

> 1 extra division is still about 70% faster than 2 multiplications,

Not true. As I said about, you only slowed down the performance. Declaring variables doesn't take any of your sources. So you can have a lot of variables, but same performance.  Amount doesn't matter, but it's always better to use up less variables for better readability.

**Comment by NatsuTheGreat** [comment]
@Barbosik Especially that he is worrying about what operation variables use. He legit only renamed variables, nothing else was really done.

**Comment by Barbosik** [comment]
@NatsuTheGreat: _micro level optimizations_

Exactly. This is the name for those attempts to "optimize" code which already works fast. He just don't understand that optimization can be done by algorithm change for most slow part of code. But the worse thing is that he trying to "optimize" by hard-coding constants and other things which is already performed by javascript JIT compiller.

**Comment by NatsuTheGreat** [comment]
@Barbosik do function calls like this slow anything down? 

```this.quadTree.find(cell1.quadItem.bound, function (item) {```

I am still working on making the collision work faster.
And I am doing good because before 500 ejected mass cells cause around 20+ MS Update Time, now I have have about 1100 ejected cells and have 20 - 25 MS Update time. I am aiming for faster :)

**Comment by Barbosik** [comment]
@NatsuTheGreat: yes, this function is the main cpu consumer, it doing all heavy job.

**Comment by NatsuTheGreat** [comment]
@Barbosik Thank you for telling me. There are quite a few of them in updateMoveEngine. I have already gotten rid of for player cell collisions. I will be working on other collision and see how many of them I can knock down. :)

**Comment by NatsuTheGreat** [comment]
Actually it looks like I have done all I can. That function is 3x faster than what I have tried :/

**Comment by IAP-Reloaded** [comment]
@ZfsrGhS953 and @Luka967 You realize that @Barbosik can sue you if they want.

**Comment by ZfsrGhS953** [comment]
Also, you said that there's a lot of checks in the onEat handler. That's because I implemented petridish.pw gamemodes. It's checking if a certain gamemode is enabled, because every gamemode has something different that occurs when eating. Why I don't just throw my gamemodes in "gamemode" folder? Because I need to combine some of these gamemodes, such as BlackHole and Experimental at the same time. With MultiOgar gamemodes, it's going to take(assuming 8 gamemodes) 8*8=64 files. It will take a long time to do that, and all of these gamemode combinations are loaded into RAM, which means on startup it will consume more memory(actually a bit more, less that 15MB I think)

**Comment by ZfsrGhS953** [comment]
@IAP-Reloaded No, I don't realise that @Barbosik can sue me. I only can realise that Zippyshare can delete my uploaded files for uploading without copyright header. However now they can't, because I added header back in.

**Comment by Barbosik** [comment]
@ZfsrGhS953: thanks

**Comment by ZfsrGhS953** [comment]
Did you download and see it? I mean like test performance compared to multiogar, gamemode settings etc.... Because I'm sure you don't believe me anymore.

**Comment by Andrews54757** [comment]
@Barbosik 


1. Isnt it open sourced?
2. Even if he did change the vars, he still didn't make it from yours (and you have no proof)
3. Quad trees are not copyrighted, Search up "quadtree" and you will find many things like yours
4. I think it is much nicer if everyone cooperates without legal barriers

**Comment by Andrews54757** [comment]
@Luka967 If it was inspired by @Barbosik . At least mention his name in the top like so:

```
// Inspired by Barbosik's quadtree
```

**Comment by Andrews54757** [comment]
Make a compromise.

**Comment by Andrews54757** [comment]
My rule of thumb:

"You cannot copy my things, but if you made it better, a lot. and others agree, than you can do it, and put your name on it too"

**Comment by Andrews54757** [comment]
Im pretty much done with Ogar though, Now I am dealing with a more professional audience

**Comment by Andrews54757** [comment]
I am currently developing a new QTree that is made on my own and has no license. (my old quadmap project failed, so Im starting from scratch) 
https://github.com/AJS-development/QuadTree.

**Pull request merged**
