### PR TITLE
Bot update

### PR DESCRIPTION
**Pull request by Luka967**
- Bots now have intelligent pathfinding - will ignore viruses in most cases
- Bot updating is now async and happens every 50ms
- Removed most of bot properties which use a lot of CPU
- Bots won't shoot viruses to threats anymore; the current program layout of the bot makes it hard to implement
- Double cell collision

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
@Luka967 Can you look at your pull requests with cell stopping in one place when cursor in the middle.

**Comment by Andrews54757** [comment]
be prepared for lots of "issues" saying "Error saying cannot find module vector 2"

**Comment by Luka967** [comment]
@Andrews54757 Requires new module, "vector2-node".

**Comment by Andrews54757** [comment]
i know, but others dont

**Comment by ItzLevvie** [comment]
Merge? @vram4

**Comment by NatsuTheGreat** [comment]
So how do I install vector2-node?

**Comment by ItzLevvie** [comment]
```npm install vector2-node```

**Pull request merged**
