### PR TITLE
More updates to bots

### PR DESCRIPTION
**Pull request by Luka967**
- Bots won't passively gain mass when running anymore
- Bots will target with their largest cell when chasing enemies
- Bots will update once one of three possibilities are made:
 - Bot is staying in one place
 - Target is out of range/eaten
 - 10% random chance

Not mentioned in the readme.txt, they won't update while server is paused anymore.

### CODE REVIEW

**Comment by Luka967** [comment]
@NatsuTheGreat How so?

**Comment by NatsuTheGreat** [comment]
One sec.

**Comment by Agarian** [comment]
Theyre better

**Comment by NatsuTheGreat** [comment]
Not with me

**Comment by NatsuTheGreat** [comment]
I downloaded a fresh ogar.

**Pull request merged**
