### PR TITLE
Fixes some of #536

### PR DESCRIPTION
**Pull request by NatsuTheGreat**
Report any bugs ;)

### CODE REVIEW

**Comment by Megabyte918** [comment]
These are all tested and they work? I can cross them off the list?

**Comment by NatsuTheGreat** [comment]
I think so!

**Comment by Megabyte918** [comment]
really wish I could test .-.

**Comment by Megabyte918** [comment]
Alright :) ill do it once its merged

**Comment by Megabyte918** [comment]
@NatsuTheGreat why'd u close?

**Comment by NatsuTheGreat** [comment]
It wasn't getting merged and it had been like a month.

**Comment by Megabyte918** [comment]
oh alright

**Pull request closed without merging**
