### PR TITLE
Integrate protocol version 7

### PR DESCRIPTION
**Pull request by Luka967**
Includes some tweaks on move engine and spectating.
Known issue is that `board` command is now not working. Reason for it is that playertrackers all generate own leaderboard packet.
Also, the client misbehaves the FFA leaderboard packet by removing first three characters even though it's been nicely sent.

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Errors:
```
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:365:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

Leaderboard not picking up the correct names:
image

**Comment by ItzLevvie** [comment]
Error when eating pellets or other cells:
```
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Users\Amal\Desktop\Ogar-master\src\GameServer.js:365:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

Leaderboard not picking up the correct names:
image

**Comment by Luka967** [comment]
I'll fix bugs that I encounter if I have time tonight. If not then tomorrow morning.

**Comment by Megabyte918** [comment]
@ItzLevvie where did you find those configs :O

**Pull request merged**
