### PR TITLE
Anti-teaming update

### PR DESCRIPTION
**Pull request by Luka967**
Also a small update on viruses.

### CODE REVIEW

**Comment by Andrews54757** [comment]
Hat does this do

**Comment by NatsuTheGreat** [comment]
WHOA WHOA WHOOAAA @Luka967 You seriously made anti teaming? :O

**Comment by Luka967** [comment]
@NatsuTheGreat Yup, it's really exaggerated though, it can give you massive anti-teaming if you just press space once in some cases.
@Andrews54757 You'll lose mass if you oversplit, explode too much on viruses or press too much W, your mass will melt.

**Comment by NatsuTheGreat** [comment]
@Luka967 Is there a fix for that?

**Comment by Luka967** [comment]
@NatsuTheGreat Just fixed it.

**Comment by NatsuTheGreat** [comment]
I wish vram4 can merge it already. I feel too lazy to change stuff piece by peace.

**Comment by Luka967** [comment]
@NatsuTheGreat He's in a different time zone I think, most of my PRs are merged after 22:00.

**Comment by NatsuTheGreat** [comment]
@Luka967 Oh

**Comment by NatsuTheGreat** [comment]
Imma make a pull request for some formating and an IP limiter.

**Comment by Andrews54757** [comment]
I just implemented anti teaming into my fork. Thanks @Luka967

**Comment by Andrews54757** [comment]
BTW, vram4 denied previous ip limiters

**Comment by Andrews54757** [comment]
(it apparently causes massive lag)

**Comment by NatsuTheGreat** [comment]
Well I always have used mine, and I didn't get lag. Even with 100 bots on my server...

**Comment by NatsuTheGreat** [comment]
And you have one too, @Andrews54757 and your server don't lag

**Comment by Andrews54757** [comment]
thats not it. when a request gets denied, the client doesnt give up and sends more requests.

**Comment by Luka967** [comment]
@NatsuTheGreat It's literally a DDoS. Massive requests from everywhere.

**Comment by Andrews54757** [comment]
try it on my fork. Turn showbmsg on and autoban on and use bots. Then look at the console then you will have an idea

**Comment by Andrews54757** [comment]
That it why @vram4 denies banning or iplimts. (ogar used to have the feature but he removed it)

**Comment by NatsuTheGreat** [comment]
oh

**Comment by Andrews54757** [comment]
I have an idea to have ip limits without a ddos attack

**Comment by NatsuTheGreat** [comment]
yeah?

**Comment by Andrews54757** [comment]
Instead of denying the request, accept the request but just dont let them spawn or keep them in a "Jail"

**Comment by NatsuTheGreat** [comment]
lol

**Comment by Andrews54757** [comment]
Im working on that but I feel too lazy

**Comment by Luka967** [comment]
@Andrews54757 Agar.io does that in 60% of the cases. It's an awesome idea tho.

**Comment by Andrews54757** [comment]
( I already added a ton of features in my fork, i feel exausted)

**Comment by Luka967** [comment]
@Andrews54757 I'll get on work.

**Comment by NatsuTheGreat** [comment]
That's a pretty good idea, no wonder I see frozen cells everywhere on agar.io

**Comment by Andrews54757** [comment]
its quite simple. all you need to do is edit a little bit of code with the spawning but my lazyness is overpowering

**Comment by Andrews54757** [comment]
(or edit the onmove funtion in playercell.js)

**Comment by NatsuTheGreat** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0 @Andrews54757

**Comment by Andrews54757** [comment]
lel

**Comment by Andrews54757** [comment]
fine I will "JUST DO IT!!!"

**Comment by NatsuTheGreat** [comment]
xD

**Comment by Andrews54757** [comment]
I did it (that was fast)

**Comment by NatsuTheGreat** [comment]
Really? Test it out lol

**Comment by NatsuTheGreat** [comment]
@Luka967 @Andrews54757 I am playing on your fork and I don't see anti teaming kicking in.

**Comment by Andrews54757** [comment]
I didnt upload yet

**Comment by Andrews54757** [comment]
Im working on the kinks

**Comment by Andrews54757** [comment]
I got the mech to work but i need to change the old mech to the new mech

**Comment by Luka967** [comment]
@NatsuTheGreat Is `serverTeamingAllowed = 0` in your config?

**Comment by NatsuTheGreat** [comment]
yes, it's 0

**Comment by Luka967** [comment]
Wtf... It's all normal here...

**Comment by NatsuTheGreat** [comment]
I don't notice the fast decaying at all really.

**Comment by Luka967** [comment]
@NatsuTheGreat looooooooooooooooool

**Comment by NatsuTheGreat** [comment]
what

**Comment by Luka967** [comment]
Nothing ignore me.

**Comment by NatsuTheGreat** [comment]
Tell me what's wrong though

**Comment by Luka967** [comment]
The fact that you didn't see the decay. xD

**Comment by NatsuTheGreat** [comment]
I don't see it ^-^

**Comment by NatsuTheGreat** [comment]
The decay goes slow

**Comment by Andrews54757** [comment]
he is right. also i need to go

**Comment by Luka967** [comment]
Try the following:
- Split into 16 pieces really quickly.
- Split eat a virus.
- Self-feeding / Pressing W in random directions.
- Feeding a mother cell.
Also enable `Show Mass` option to see more precisely.

**Comment by NatsuTheGreat** [comment]
Alright. I will try.

**Comment by NatsuTheGreat** [comment]
nope

**Comment by Luka967** [comment]
Downloaded my fork, played for a little, I immideately saw anti-teaming. I'll even give a gif soon.

**Comment by NatsuTheGreat** [comment]
Gimme your fork plux

**Comment by ItzLevvie** [comment]
@NatsuTheGreat https://github.com/Luka967/Ogar/archive/master.zip (https://github.com/Luka967/Ogar)

**Comment by NatsuTheGreat** [comment]
Holy shit. It is so strict.

**Comment by Luka967** [comment]
But almost the same as agar.io ;)

**Comment by NatsuTheGreat** [comment]
good job. Just a little too strict.

**Comment by Andrews54757** [comment]
I added no lag ip limit to my fork (you cant spawn)

**Comment by Luka967** [comment]
I'm fixing some things for this *(exchanging ejected cells with the same team is not punished)* and I see I'm on a path for making ejected cell collision.
Should I try doing it?

**Comment by ItzLevvie** [comment]
@Luka967 Sure.

**Comment by Andrews54757** [comment]
Ejected cell collision is already done, see my fork

**Comment by Luka967** [comment]
@Andrews54757 gonna make it even better :3

**Comment by Andrews54757** [comment]
Good luck!

**Comment by Luka967** [comment]
@Andrews54757 Thank you, though where is that code for ejected cell collision? Can't seem to find it lol

**Comment by NatsuTheGreat** [comment]
Go on Andrew's fork

**Comment by Andrews54757** [comment]
Its at calcmovephys function at either playercell.js or cell.js

**Comment by Andrews54757** [comment]
(I dont know)

**Comment by ItzLevvie** [comment]
@Luka967 https://github.com/OgarProject/Ogar/issues/345#issuecomment-171059916

**Comment by NatsuTheGreat** [comment]
calcMovePhys is in cell.js

**Comment by Andrews54757** [comment]
Okay

**Comment by Luka967** [comment]
Thx everyone xD

**Comment by NatsuTheGreat** [comment]
Yep

**Comment by Luka967** [comment]
So far going cool.

**Comment by NatsuTheGreat** [comment]
Okay

**Comment by Andrews54757** [comment]
BTW there is an error that pops up sometimes saying "Playertracker is undefined" but I fixed it on my fork

**Pull request merged**
