### PR TITLE
Rewrote Tournament gamemode

### PR DESCRIPTION
**Pull request by yoyosh**
Rewrote Tournament gamemode (it was full of bugs and terribly-coded)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@vram4

**Comment by Luka967** [comment]
@vram4

**Comment by ItzLevvie** [comment]
@vram4

**Comment by MastaCoder** [comment]
@vram4

**Comment by Andrews54757** [comment]
NOOOOOOOOOOOOO

**Pull request closed without merging**
