### PR TITLE
Fixed bug when adding bots to Teams, Zombie or Zombie Teams.

### PR DESCRIPTION
**Pull request by ItzLevvie**
Without this, you'll get an error
```
TypeError: cell.simpleCollide is not a function
    at Mode.Teams.onCellMove (C:\Users\XXXX\Desktop\Ogar-master\src\gamemodes\Teams.js:105:23)
    at Cell.PlayerCell.calcMove (C:\Users\XXXX\Desktop\Ogar-master\src\entity\PlayerCell.js:84:25)
    at GameServer.updateMoveEngine (C:\Users\XXXX\Desktop\Ogar-master\src\GameServer.js:531:14)
    at GameServer.cellTick (C:\Users\XXXX\Desktop\Ogar-master\src\GameServer.js:351:10)
    at GameServer.mainLoop (C:\Users\XXXX\Desktop\Ogar-master\src\GameServer.js:385:29)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

### CODE REVIEW

**Comment by vram4** [comment]
@NatsuTheGreat The simplecollide function has nothing to do with "smooth" collision, it detects whether or not cells should be checked for collision, not the behavior that happens when they collide.

**Comment by NatsuTheGreat** [comment]
So the collision that Tiberiu02 made is going to be still there right?

**Comment by vram4** [comment]
It should be.

**Comment by NatsuTheGreat** [comment]
Okay

**Pull request merged**
