### PR TITLE
Made ejectMassCooldown off by default.

### PR DESCRIPTION
**Pull request by BaumanDev**

### CODE REVIEW

**Comment by Andrews54757** [comment]
If there is no cooldown, people can take advantage of that and use software like agario powerups to spam w

**Comment by NatsuTheGreat** [comment]
Dude, agar.io powerups isn't in the store, and if you get it through zip, when you load http://agar.io the page is blank white. This was long ago before all extensions broke.

**Comment by Luka967** [comment]
There is a script which enables you to hold E and eject 6 times in a second.

**Comment by NatsuTheGreat** [comment]
but what's the problem with w?

**Comment by Luka967** [comment]
Well, nothing, just pointing out.

**Comment by Andrews54757** [comment]
its not a good idea.... anyway, the timeout barely affects you

**Comment by NatsuTheGreat** [comment]
tell me why it's a bad idea

**Comment by Andrews54757** [comment]
like i said. people can use scripts to spam w. and that means what? 1. it means more server lag. 2. it means unfair shooting of viruses 3. it means easier teaming

**Comment by NatsuTheGreat** [comment]
whatever like the owner can't change it -.-

**Comment by ItzLevvie** [comment]
Close? @vram4

**Pull request closed without merging**
