### PR TITLE
Resolve #620, fix bugs, improve anti-teaming

### LINKED ISSUE #620: Remove comma at the end of line 7 in package.json
NPM for node.js doesn't like the comma there. Causes parsing error.

### PR DESCRIPTION
**Pull request by Luka967**
Want to hear about the new anti-teaming - how solo can it be?
- Doesn't punish players exploding constantly unless you lose some mass
- Doesn't punish self-feeding harshly

Check these things:
- Lose or gain mass quickly
- W team with bot/player
- Do some cell giving with teammate

### CODE REVIEW

**Comment by SorryAgario** [comment]
untitled
NOPE

**Comment by Luka967** [comment]
@SorryAgario fixed it at commit 13d25d0

**Comment by SorryAgario** [comment]
worked. thanks

**Comment by SorryAgario** [comment]
add minions?

**Pull request merged**
