### PR TITLE
Fixes on spectating

### PR DESCRIPTION
**Pull request by Luka967**

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
C:\Users\\Downloads\Ogar-master\Ogar-master\src>node index.js
C:\Users\\Downloads\Ogar-master\Ogar-master\src\PlayerTracker.js:419
});
 ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\\Downloads\Ogar-master\Ogar-master\src
\GameServer.js:9:21)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

C:\Users\German\Downloads\Ogar-master\Ogar-master\src>pause
Press any key to continue . . .

New error. :(

**Comment by Luka967** [comment]
I don't have any errors.


*I'm going to die because of these errors today.*

**Comment by NatsuTheGreat** [comment]
Does the roam work for you?

**Comment by Luka967** [comment]
Yup, in any gamemode.

**Comment by Luka967** [comment]
Yup, in all gamemodes.

**Comment by Andrews54757** [comment]
@Luka967 can you please please please make a pull request that adds spectate roaming in my fork

**Comment by Luka967** [comment]
@NatsuTheGreat Sure!

**Comment by Andrews54757** [comment]
Im andrews54757 lol

**Comment by Andrews54757** [comment]
and my fork is ogar unlimited

**Comment by NatsuTheGreat** [comment]
:$ He likes me

**Comment by Andrews54757** [comment]
lol

**Comment by Andrews54757** [comment]
:}

**Comment by Luka967** [comment]
@Andrews54757 I didn't even see this. :1234: is too hard for me

**Comment by Andrews54757** [comment]
what do you mean?

**Comment by Andrews54757** [comment]
it is this https://github.com/AJS-development/Ogar-unlimited

**Comment by Andrews54757** [comment]
It is now pretty popular though

**Comment by NatsuTheGreat** [comment]
it is not popular or now popular? I am a lil confused.

**Comment by Andrews54757** [comment]
it is poplular

**Comment by NatsuTheGreat** [comment]
Oh

**Pull request merged**
