### PR TITLE
Add unix start script

### PR DESCRIPTION
**Pull request by kkprince1998**
Added a easy to use start script for people running linux. it automatically selects the executable ``nodejs`` if it is available, otherwise it will try the traditional ``node``.

### CODE REVIEW

**Comment by jcc10** [comment]
I wish there was a vote system. I would up-vote this.

**Comment by teaganpealo** [comment]
Okay

**Comment by makmm** [comment]
same +1

**Comment by jcc10** [comment]
Can we merge this now?

**Pull request merged**
