### PR TITLE
REFACTORED - mother cell in own file

### PR DESCRIPTION
**Pull request by scholtes**

### CODE REVIEW

**Comment by Andrews54757** [comment]
Yay, ogar is finally catching up with others such as ogar unlimted

**Comment by Luka967** [comment]
Well it was catching up with agar.io from the beginning

**Comment by ThunderGemios10** [comment]
@Andrews54757 Catching up with your own work? well at least you are generous to say that.

**Comment by NatsuTheGreat** [comment]
> such as ogar unlimted
Every chance to advertise it.. So annoying..

**Comment by ItzLevvie** [comment]
Close? @vram4

**Comment by ItzLevvie** [comment]
Close? @vram4

**Pull request closed without merging**
