### PR TITLE
feature: add the ability for food to grow like agar.io

### PR DESCRIPTION
**Pull request by mrmarktyy**
Introduced four config attributes for this feature,

```
foodMassGrow: 0, // Enable food mass grow ?
foodMassGrowPossiblity: 50, // Chance for a food to has the ability to be self growing
foodMassLimit: 5,  // Maximum mass for a food can grow
foodMassTimeout: 120, // The amount of interval for a food to grow its mass (in seconds)
```

### CODE REVIEW

**Comment by AgarioCheats** [comment]
Very nice implementation, @mrmarktyy.

By the way, what exactly is the collision engine, and collision between cells?

**Comment by mrmarktyy** [comment]
@NatsuTheGreat just made a PR to fix this issue (#350)

**Comment by mrmarktyy** [comment]
@AgarioCheats collision engine in Ogar was basically the detection of collided cells and reposition collided cells so that they were apart. It should apply to all cells without `ignoreCollision` flag.

**Comment by mrmarktyy** [comment]
@NatsuTheGreat yes, you can play with the attribute `foodMassGrowPossiblity` to figure out the best fit to your server. (there's a bug with this possibility, please wait #350 merged in to get it right)

**Comment by NatsuTheGreat** [comment]
@mrmarktyy I really need help with the collision check out (#349) for more info of what i have done SO far

**Pull request merged**
