### PR TITLE
Add `kickrange` and `killrange` commands

### PR DESCRIPTION
**Pull request by jacob-greenfield**

### CODE REVIEW

**Comment by MastaCoder** [comment]
This is great! Especially for users with bots and you want to remove all the bots at the same time!

**Comment by Coder-256** [comment]
I made these a while ago though, so I'm not sure if they're still compatible.

**Comment by Andrews54757** [comment]
There is a typo thought, because you used `split[]` wrong, it must be `split[0]` then `split[1]` for the second variable instead of both variables being `split[0]`

**Comment by ItzLevvie** [comment]
Close? @vram4

**Pull request closed without merging**
