### PR TITLE
Update BotLoader.js

### PR DESCRIPTION
**Pull request by m-byte918**
Bots reuse the same names if there are more bots than botnames

### CODE REVIEW

**Comment by MastaCoder** [comment]
We need this!

**Comment by WaitCC** [comment]
Agreed, this is a great idea.

**Comment by Megabyte918** [comment]
Yeah I only wish someone would MERGE it 
*cough cough* @vram4 *cough cough*

**Comment by ThunderGemios10** [comment]
I think it's safe to say that OgarProject is dead.

**Comment by MastaCoder** [comment]
@ThunderGemios10 Basically yes. I don't like how they don't pass on management to someone that is far more active so they can at least accept pull requests..

**Comment by ItzLevvie** [comment]
Nope not dead. http://agar.io/v72/

**Comment by ThunderGemios10** [comment]
@ItzLevvie Is that an old version? And its still live?

**Comment by ItzLevvie** [comment]
@ThunderGemios10 Yes, it's the old version.

**Comment by MasonBurdette** [comment]
@ItzLevvie they removed it from their servers :(

**Comment by firelightning13** [comment]
RIP v72

**Comment by MasonBurdette** [comment]
@firelightning13 not actually, my friend still has all of the html, css, and js of v72

**Comment by firelightning13** [comment]
ok cool

**Comment by Luka967** [comment]
@MasonBurdette Awesome

**Comment by Andrews54757** [comment]
RIP v72

**Comment by NatsuTheGreat** [comment]
See that one thing about this bot name thing, the bot names are randomly chosen whatsoever. The splice thingy took it out of the index and the name could no longer be used. Now the names will be reused because you have Math.random() there and it picks random name and uses. That COULD reuse some of the names even if you have less bots than the length of the random names.

**Comment by Agarian** [comment]
*cough cough* MERGE?

**Comment by Agarian** [comment]
Well nvm vram

**Pull request closed without merging**
