### PR TITLE
Revamp the way cells merge

### PR DESCRIPTION
**Pull request by Luka967**
Instead of counting down the ticks left to merge until 0, count from 0 until it reaches the threshold. Making a way of merging a lot more similar to agar.io one.

### CODE REVIEW

**Comment by Luka967** [comment]
Found the problem at line 766:
it should be
```javascript
if ((!cell.shouldRecombine) || (!check.shouldRecombine)) {
```

**Comment by mrmarktyy** [comment]
Can someone please explain why counting from 0 makes a different. thanks!

**Comment by Luka967** [comment]
@mrmarktyy It's an instant recombine now. Why?

**Comment by Luka967** [comment]
Wait crap. I totally went away from what you ask. Sorry all for double post.

The reason is that Ogar was implementing merging on a, literally, simple timer.
Now you need to wait a few phases of merging to do it completly. Like in real agar.io; you won't merge ~10 of your cells in one go, as Ogar before did.

**Comment by mrmarktyy** [comment]
@Luka967 cool, so with these code, ~10 cells won't merge in one go ?

**Comment by Luka967** [comment]
Yup

**Pull request merged**
