### PR TITLE
Check your JSON!

### PR DESCRIPTION
**Pull request by Maxetto**
This made my auto-updater script break, along with 4 days of unreported downtime! :/

### CODE REVIEW

**Comment by Maxetto** [comment]
Closed as redundant of #621

**Comment by Luka967** [comment]
We're really sorry for the downtime though!

**Comment by Maxetto** [comment]
It's not your fault, players should have reported it, while they didn't.

**Comment by Luka967** [comment]
They reported it however vram4 isn't there to accept the pull request - if he was there sooner, it would be fixed.

**Comment by Maxetto** [comment]
I mean players from my server :stuck_out_tongue:

**Comment by Luka967** [comment]
hehehe xD

**Comment by F0RIS** [comment]
@Maxetto can you share your auto-updater script ?

**Comment by Maxetto** [comment]
This is the update script: http://pastebin.com/4kUJ2Cmx
It requires 2 folders, one with source (/root/ogarsource) and one with the actual game (/root/ogar). You have to change them to your needs.
You also have to start it in a screen and set-up an init.d script (service).

Here's mine: http://pastebin.com/DN0u9m68
You have to change the folder to your needs here too.

Eventually you can make an init.d script for the updater too in order to start it along with the machine boot.

**Pull request closed without merging**
