### PR TITLE
Server restarting without external looping

### PR DESCRIPTION
**Pull request by Luka967**
Memory leak-proof, don't worry, doesn't show any problems of it for me.

- Adds new command `restart`
  - Has many uses, see `restart help` or `restart ?` for info
- Also reverts Andrews' async console input because:
  - Repeated command inputs will appear multiple times when looking for command with arrow-up key
  - Backspace doesn't work
  - Possible memory leaks
  - I/O being backed up by server processing should not happen anymore, and even if it is, EVERYTHING will be backed up irreversibly until server processing ends, thus making it async is useless as node.js is single-cored
- Added `--expose-gc` argument to enable force garbage collecting when restarting
- Added config for periodical restarting of the server

### CODE REVIEW

**Comment by Andrews54757** [comment]
@Luka967 I figured the async console didn't work because you were on windows. Apparently, windows uses different ANSI codes. Screw them. So instead of just checking for `\u007F` (which is what all the others use), you have to also check for `\u0008`. But anyway, I will make another pr in the way future after I perfect the console.


And you are mistaken about how nodejs works. Async items are much more efficient than non Async. Especially readline. Also, using looping-readline creates callback hell. And in the future, the setTimeout(item,0) will be deprecated, rendering this method useless.

**Comment by Andrews54757** [comment]
@Luka967. I am currently fixing the issues you described here: https://github.com/AJS-development/AsyncConsole/blob/master/index.js

**Comment by Andrews54757** [comment]
Also, I hope you realize that isn't a true restart. The server won't be garbage collected if there are any loops running inside.

**Comment by NatsuTheGreat** [comment]
Hello

**Comment by NatsuTheGreat** [comment]
I don't know?

**Comment by NatsuTheGreat** [comment]
Test :D

**Comment by NatsuTheGreat** [comment]
Hi

**Comment by NatsuTheGreat** [comment]
Oooh

**Comment by NatsuTheGreat** [comment]
Test

**Comment by Luka967** [comment]
@Andrews54757 Yes, I know this isn't a true loop. I'm still looking for memory leaks. There aren't any if the server is dormant without any bots or players. If there are, the server doesn't get marked as unused, and makes another server object on top of this one. I'm still looking on the fix.

**Comment by Andrews54757** [comment]
I know how to fix.

**Comment by Andrews54757** [comment]
Look at the heaps for OpenAgar. Here, I created 3 servers from one (multi server feature), and removed them one by one.


All three servers:

screen shot 2016-11-28 at 10 37 49 am

Removed one server:

screen shot 2016-11-28 at 10 38 01 am

Removed the other server:

screen shot 2016-11-28 at 10 38 09 am

**Comment by Andrews54757** [comment]
Next, I am gonna test Ogar's restart

**Comment by Andrews54757** [comment]
@Luka967 What I suspected of your restart system is true: There is a memory leak.


Before restart:

screen shot 2016-11-28 at 10 48 21 am

After restart:

screen shot 2016-11-28 at 10 48 41 am

**Comment by Andrews54757** [comment]
I did more tests, and I found out that a single game server instance costs about 500 KB. So I am going to find out how much memory Ogar uses if I restart 5 times or so

**Comment by Andrews54757** [comment]
After I restarted Ogar 5 times, this is what happened:

screen shot 2016-11-28 at 10 59 57 am


This is without bots or players. Imagine the memory if there were.

**Comment by Andrews54757** [comment]
The memory jumped from 7543 KB to 11288 KB. The difference is 3745 KB!. Divide that by 5 equals 749KB! So every time your restart, it adds 749KB.

**Comment by Andrews54757** [comment]
You need to fix your restart command. Also its `sudo node --expose-gc index.js` not sudo node  index.js --expose-gc`.

**Comment by Andrews54757** [comment]
I will make a pr with those fixes

**Comment by Luka967** [comment]
I've tweaked it to log all `setTimeout` and `setInterval` calls and store all IDs into memory to kill them on restart. Shows great improvement after 2nd restart even with bots or players. I don't have enough time to test them more, I'll be back in 4 hours.

**Comment by Andrews54757** [comment]
@Luka967 I thought you didn't want to waste your time on a dead project.

**Comment by Luka967** [comment]
@Andrews54757 I also thought you've quit making Ogar-related projects to actually do something in your life. I'm still bored.

**Comment by Andrews54757** [comment]
@Luka967 I quit Ogar. I am trying to transform an old concept (agar.io) and turn it into something else.

**Pull request merged**
