### PR TITLE
Partially fix #536 + massive perfomance fix

### LINKED ISSUE #536: Physics/bugs/suggestions
Hello, i've gathered a list of stuff that are bugs and suggestions on the physics of Ogar. Most of these are from [this,](https://github.com/AJS-development/Ogar-unlimited/issues/268) but i thought i'd bring mine and some other people's here just to shed some light. If anybody has anything else to add on, please, leave it here :)

Credit: @fodse
> - If a player spawns from an Ejected Mass, he will always have the size of that mass (13 by default), and not the size that is displayed on "PlayerStartMass" in "Gameserver.ini" (which is 43 in my case).
- 80% of the time you'll spawn very close to some other player/bot or even dead. (The same happens with viruses).
- In vanilla Agar.io, when you split with the cursor in the middle of the cell, it doesn't split horizontaly, it actually splits to alot of directions and then freezes.

Credit: @Lukkez
> - Cells still move when getting hit by a virus while mouse is in center. (used to work in previous versions of ogar but now it doesnt?)

Credit: @firelightning13
> - <del>When splitting a new cell, the new cell shouldnt be move by cursor (or move a little bit) until cRestoreTicks is finish ticking. I don't know it is a mech from vanilla agar.io but you'll notice when you're too big. </del>
- The camera sometimes only focus to the smaller cell instead of the big one (possibly giving priority for the big cell?) (you'll notice when you have 2 pieces which is huge cell with very small cell at another one)

And here is a list of mine:
- [Virus explosions] (https://github.com/AJS-development/Ogar-unlimited/issues/242) could be a little better when big
- Splitpops do not work 90% of the time like they should
- Virus throws do not work
- Doublesplits could be more accurate
- Cells need to have a little more "bounce back" or "spring" to them when doublesplitting or tricksplitting. And just splitting in general.
- When in max pieces, and max size in each of those pieces, cells cant surpass 360k mass. They should be able to #527 
- Cells on the same team on teams mode can prevent another cell from moving, this is very annoying cause sometimes bots like to stick to you
- Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed
- Bots are lazy and don't split for people most of the time
- In vanilla agario, when doublesplitting, some of your cells have a chance of switching order, which allows you to splitkill someone when you doublesplit at them over a virus.
- Splitting and w-ing against the border of the map should be more bouncy
- The range of which a cell consumes another cell is too short (**possible config for this?**)
- Needs a better anti-bot system, servers can still get infested with suicide bots even when all anti-bot systems are active
- Splitspeed and distance between cells when splitting needs to be increased. The seperation of the cells when splitting is slow af right now
- Player speed needs to be 35 by default, as it is more similar to the regular speed of vanilla agario
- When out of bot names in realisticnames.txt or botnames.txt, they should reuse the same names instead of bot[#], (bot then number of bot)

### PR DESCRIPTION
**Pull request by Luka967**
Partially fixes #536 . _I'm not dead._
- Zoom and node range at free roam adjusted to agar.io's
- Fixed small cells offsetting cells too much
- Some fixes here and there
- Fixed lazy splitting of bots
- Bots will now farm viruses
- A bit safer spawning for players [WIP; player cells are still spawning on viruses] which includes a warning message if it happens a lot
- Pellet eating doesn't use collisionCheck2 anymore; swapped by sqrt-based distance calculation which enables food to be eaten by any mass cell
- Shortened sorting algorithm in mainLoop
- Larger anti-teaming effect on virus explode
- Mass of new cell is max of ejected cell mass and config start mass
- Cells won't spawn on moving ejected cells
- Fixed wrong-behaving borderLeft and borderTop
- Made bouncy physics a lot more bouncier
- PlayerTracker update is now async
- Abolished config `playerSmoothSplit`
- **`getCellsInRange` in GameServer won't check for all cells in visible nodes, instead will check all cells that collide with any of client's cells**
### #536's suggestions
- [X] If a player spawns from an Ejected Mass, he will always have the size of that mass (13 by default), and not the size that is displayed on "PlayerStartMass" in "Gameserver.ini" (which is 43 in my case).
- [ ] 80% of the time you'll spawn very close to some other player/bot or even dead. (The same happens with viruses). **Partially fixed**
- [ ] In vanilla Agar.io, when you split with the cursor in the middle of the cell, it doesn't split horizontaly, it actually splits to alot of directions and then freezes.
- [ ] Cells still move when getting hit by a virus while mouse is in center. (used to work in previous versions of ogar but now it doesnt?)
- [X] Virus explosions could be a little better when big
- [ ] Splitpops do not work 90% of the time like they should
- [ ] Virus throws do not work
- [X] Doublesplits could be more accurate
- [X] Cells need to have a little more "bounce back" or "spring" to them when doublesplitting or tricksplitting. And just splitting in general.
- ~~When in max pieces, and max size in each of those pieces, cells cant surpass 360k mass. They should be able to #527~~ (It was actually fixed even before)
- [X] Cells on the same team on teams mode can prevent another cell from moving, this is very annoying cause sometimes bots like to stick to you
- [X] Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed
- [X] Bots are lazy and don't split for people most of the time
- ~~In vanilla agario, when doublesplitting, some of your cells have a chance of switching order, which allows you to splitkill someone when you doublesplit at them over a virus.~~ (Can't understand)
- [X] Splitting and w-ing against the border of the map should be more bouncy
- [X] The range of which a cell consumes another cell is too short (possible config for this?)
- [ ] Needs a better anti-bot system, servers can still get infested with suicide bots even when all anti-bot systems are active
- [X] Splitspeed and distance between cells when splitting needs to be increased. The seperation of the cells when splitting is slow af right now
- [X] Player speed needs to be 35 by default, as it is more similar to the regular speed of vanilla agario
- ~~When out of bot names in realisticnames.txt or botnames.txt, they should reuse the same names instead of bot[#], (bot then number of bot)~~ (Purely cosmetic things)

P.S. http://agar.io/?ip=ogar-luka967.c9users.io:8080 is my test server. I open it when I'm working on Ogar.

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Merge? @vram4

**Comment by Luka967** [comment]
@vram4 If you plan on quitting Github, at least make somebody a collaborator so that PRs can be accepted.

**Comment by Luka967** [comment]
- [X] Virus explosions could be a little better when big
- [ ] Splitpops do not work 90% of the time like they should
- [ ] Virus throws do not work
- [X] Doublesplits could be more accurate
- [X] Cells need to have a little more "bounce back" or "spring" to them when doublesplitting or tricksplitting. And just splitting in general.
- [X] ~~When in max pieces, and max size in each of those pieces, cells cant surpass 360k mass. They should be able to #527~~ (It was actually fixed even before)
- [X] Cells on the same team on teams mode can prevent another cell from moving, this is very annoying cause sometimes bots like to stick to you
- [X] Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed
- [X] Bots are lazy and don't split for people most of the time
- [ ] ~~In vanilla agario, when doublesplitting, some of your cells have a chance of switching order, which allows you to splitkill someone when you doublesplit at them over a virus.~~ (Can't understand)
- [X] Splitting and w-ing against the border of the map should be more bouncy
- [X] The range of which a cell consumes another cell is too short (possible config for this?)
- [ ] Needs a better anti-bot system, servers can still get infested with suicide bots even when all anti-bot systems are active
- [ ] Splitspeed and distance between cells when splitting needs to be increased. The seperation of the cells when splitting is slow af right now
- [X] Player speed needs to be 35 by default, as it is more similar to the regular speed of vanilla agario
- [ ] When out of bot names in realisticnames.txt or botnames.txt, they should reuse the same names instead of bot[#], (bot then number of bot)

**Comment by NatsuTheGreat** [comment]
The bots still need improvement :p
- They have trouble with the border (some just stay there)
- They split for anything without and consideration of threats.
- Suicide sometimes
- Big bots are lazy splitters
- They do not split away when being split-killed.
- Trouble avoiding viruses
- Haven't seen any bots shoot viruses.

**Comment by ItzLevvie** [comment]
in vanilla agario your front two cells switch order when doublesplitting, which allows you to still be able to eat someone when you doublesplit at them over a virus and switch your first two cells so that it looks like this after doublesplitting: ooOo

**Comment by Luka967** [comment]
@ItzLevvie I never saw that happening.
@NatsuTheGreat 
- Suiciding is easily addable however I'm lazy to do it xD
- Saw it, looking for solutions.
- Avoiding system is crappy with viruses but avoids everything
- I think I fixed it?
- Juking has been removed and is also easily addable
- Bots won't shoot viruses anymore

**Comment by NatsuTheGreat** [comment]
@Luka967 Can you work on making the cells freeze if the cursor is in the middle? I think you need a specific point to trigger it at which will be the cursor is in centerPos, then that should be triggered. Then you return nothing in calcMove. The last time it worked but the cell went like 50% slower. And sometimes they didn't collide although I just split.

**Comment by ItzLevvie** [comment]
https://goo.gl/sidTFm xD

**Comment by firelightning13** [comment]
@ItzLevvie What extension did you use? I want one :(

**Comment by Megabyte918** [comment]
@Luka967 this is with the cells in this order: (1)(2)(3)(4)
when doublesplitting over somebody at close range, the fourth cell will consume the player, but it will switch order with your third cell, so it will look like this: (1)(2)(4)(3)
so instead of your cells looking like this when you doublesplit over somebody: oooO
it would look like this: ooOo
this happens all the time in vanilla, and in youtube videos too you'll notice it if you pay close enough attention.
it also allows for you to kill someone when you doublesplit at them over a virus (the "x" being the cell that explodes) instead of being like this: OOOx 
it would look like this OOxO

**Pull request merged**
