### PR TITLE
Update gameserver.ini

### PR DESCRIPTION
**Pull request by gggggkl**

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Close? @vram4

**Comment by XtremePlayzCODE** [comment]
this is not a good pr

**Comment by NatsuTheGreat** [comment]
Very useless.

**Comment by Agarian** [comment]
Is vram4 dead?

**Comment by Luka967** [comment]
@Agarian nah he's probably chillin'. I was too, went on a trip for 10 days

**Comment by Agarian** [comment]
oh lol

**Pull request closed without merging**
