### PR TITLE
Make the console async

### PR DESCRIPTION
**Pull request by Andrews54757**
In the comment, you said "Too lazy to learn async". Well, now its done! I originally did it for https://github.com/AJS-development/OpenAgar/blob/master/source/core/shellService.js, but I thought, "Why should I just help myself?" . So I decided to allow Ogar to have that code. 

## Advantages:

1. It is much more efficient: OpenAgar wasn't efficient at the beginning, so Readline would just freeze when there was lag. So I made it async and it worked even during lag. (Now though, OpenAgar is the most efficient agar.io server available)
2. It has all the features of readline: I even added the "remembering" feature that allows you to use the arrow keys to see the commands you made earlier

## Disadvantages:

1. Not much but there are tiny things that are easily fixable. 

## Notes:

1. I didn't add fancy text support but you can add them by adding characters to the escapeChar() function. Edit the allowed string.  Characters are separated by spaces
2. If the string is very long, it won't erase it completely if you delete one charactor. So if I had `abcdefghijklmnophdihwiishihdh`, and I delete a bunch of characters, it will become like 
`abcdef            nophdihwiishihdh` with a gap in the middle. This is also very easily fixable by editing ` process.stdout.write('\r                                   ');` (use `\r\x1b[k`?)

NOTE: THIS CODE IS COPYRIGHTED BY AJS DEVELOPMENT, BUT OGAR IS AN EXCEPTION. (Basically, do not copy in your own project to sell it. I give exclusive rights to ogar because I owe lots of my js skills to this project)

### CODE REVIEW

**Comment by Andrews54757** [comment]
Everything is tested. And it works flawlessly

**Comment by Andrews54757** [comment]
@vram4 ?

**Comment by ZfsrGhS953** [comment]
```
most efficient agar.io server available
```
I second that. I develop my own agar.io clone server implementation - [Petridish Ogar](https://github.com/ZfsrGhS953/Petridish-Ogar). While I understand that the petridish client may not be an efficient one, the server is based on MultiOgar (which is already fast by itself) and contains many optimizations. I think you should test your implementation against mine.

**Comment by Andrews54757** [comment]
@ZfsrGhS953 OpenAgar is twice as efficient as MultiOgar currently. If I find one that is more efficient, I will make it even more efficient. Note that OpenAgar is not finished. But I have very big plans for it. I optimized things from client-side to server side, and there will be more. So that:


1. Some game logic will be handled client side
2. Bots will run on a different process (cpu core)
3. Server side cache
4. Server will be slowed down a lot as the velocity and path will be predetermined client side (fps will be lower)
5. Bots will be dynamic
6. And other things.


And yes, I was impressed by MultiOgar the first time I saw it. Yet I feel like we can do much much better. I envision a server holding 1000 players and 500 bots without any lag at all.

**Comment by ZfsrGhS953** [comment]
1. That will allow cheats that are much worse than bots.
2. I have thought of that already, but didn't add it.
3. What cache? I can't think of any cache that can speed up the server a lot.
4. Interesting idea, it also saves bandwidth a lot. I think that's the main reason why it's twice as efficient as MultiOgar.
5. "Dynamic" means every bot will be able to have different AI instead of one?
6. Don't throw too much things in one server to avoid lag.

**Comment by Andrews54757** [comment]
1. There will be checks to make sure that wont happen.
3. There are lots.
4. This hasnt even been done yet, and caches are the reason why its twice as fast
5. No, some ais will be dumb, others smart for preformance
6. Too bad

**Comment by Andrews54757** [comment]
Some other things Im gonna add:

1. Nonvisible nodes are ignored (so no collision and whatnot if a player is not within some range)
2. Minions will have no update loop unlike OgarUL
3. Slow clients will be detected and will be dropped.

**Comment by Andrews54757** [comment]
The client side physics in detail:


The playercell's movement will be handles client side. Then there will be a checker server side like this:


```
var oldpos // current position
var newpos // position requested by client

var difx = Math.abs(oldpos.x - newpos.x)
var dify = Math.abs(oldpos.y - newpos.y)
if (difx > max || dify > max) return // drop because he is cheating

```

**Comment by Andrews54757** [comment]
Details for slow fps:


All moving nodes will have a velocity sent with it. Then, I will edit this code client-side


```
function (nosize) {
            if (0 == this.id) return 1;
            var a;
            a = (timestamp - this.updateTime) / 120;
            a = 0 > a ? 0 : 1 < a ? 1 : a;
            var b = 0 > a ? 0 : 1 < a ? 1 : a;
             
            this.getNameSize();
            if (this.destroyed && 1 <= b) {
                var c = Cells.indexOf(this);
                -1 != c && Cells.splice(c, 1)
            }
        
            this.x = a * (this.nx - this.ox) + this.ox;
            this.y = a * (this.ny - this.oy) + this.oy;
            if (!nosize) this.size = b * (this.nSize - this.oSize) + this.oSize;
           // console.log(this.x+"|"+this.y + "|" + canvasWidth + "|" + canvasHeight)
            return b;
        },

```

**Comment by Andrews54757** [comment]
UPDATE: I implemented the slow fps method. It is now 6 times faster

**Comment by Megabyte918** [comment]
vram4 is dead.

**Comment by Andrews54757** [comment]
Is this project dead? @vram4 ?

**Comment by Luka967** [comment]
No, vram4 is dead

**Comment by ZfsrGhS953** [comment]
The problem is much more severe. Not only Ogar is dead, "The big three", how I call it, of the private servers (Ogar, MultiOgar, Ogar-Unlimited) is dead. Last Ogar update was in 28 July, MultiOgar update was in 12 August, and Ogar-Unlimited update (aside from patches and uniban updates) in 20 August.

**Comment by Andrews54757** [comment]
Oh well, time for OpenAgar to take the lead again.

**Comment by Megabyte918** [comment]
Holy crap! He's alive!

**Comment by NatsuTheGreat** [comment]
!!!

**Pull request merged**
