### PR TITLE
Smooth splitting update

### PR DESCRIPTION
**Pull request by Luka967**
Also includes some other minor edits.
- `GameServer.js` - More split smoothness
- `GameServer.js` - Simplified cell creation function
- `Cell.js` - Formatting & created collisionRestoreTicks
- `PlayerCell.js` - Realistic eating range & usage of collisionRestoreTicks

`Virus.js`
- Referenced createPlayerCell
- Small cells now have a random angle
- The big cell loop was edited a bit

- `Experimental.js` - Even more realism at virus pushing and creating pellets

### CODE REVIEW

**Comment by Luka967** [comment]
Oh a cool thing I found out, when having a lot of pieces and typing in `merge` command for you, it will make splitting very weird xD

**Comment by NatsuTheGreat** [comment]
yeah
I just saw that.

**Comment by NatsuTheGreat** [comment]
whoa the virus explosions are so much better

**Comment by Luka967** [comment]
@NatsuTheGreat Yup, it resolved the old issue.

**Comment by NatsuTheGreat** [comment]
how did you make the shoot virus so smooth?

**Comment by Luka967** [comment]
@NatsuTheGreat If I interpreted your question as "virus shooting";
Current line `765` at `GameServer.js`, currently it is:
```javascript
newVirus.setMoveEngineData(135, 20, 0.85);
```

**Comment by NatsuTheGreat** [comment]
Oh I had that.
It's just that the virus goes faster than it does in here.

**Comment by Luka967** [comment]
@NatsuTheGreat Dunno then xd

**Comment by NatsuTheGreat** [comment]
alrighty.

**Comment by NatsuTheGreat** [comment]
Do you know why pop split doesn't work with me? I don't know if it's a problem with splitting, virus explosions, or whatever..

**Comment by Agarian** [comment]
CAN YOU PLEASE IMPLEMENT THE VIRUS SPLITTING INTO OGAR UNLIMITED? ITS EXACTLY LIKE REGULAR AGARIO AND WOULD FIT IN WITH OGAR UNLIMITED!

**Pull request merged**
