### PR TITLE
Updated collision engine

### PR DESCRIPTION
**Pull request by Tiberiu02**
I've found that the collision engine was wrong coded. After the changes I've made the collisions should be exactly like on the original agar.io

### CODE REVIEW

**Comment by Tiberiu02** [comment]
Why my changes wasn't accepted?

**Comment by NatsuTheGreat** [comment]
Hey man, it's not really like original agar.io. I mean like the splitting isn't too common, still different, no collision with ejected mass. But you you tried! xP Or maybe something didn't update.. I hope I can get it to work.

**Comment by Tiberiu02** [comment]
I meant the collisions between cells of the same player, they are like the original agar.io, not the splitting and not the ejected mass collisions. Check this picture to see how significant is my change.
collisions

**Comment by NatsuTheGreat** [comment]
Wow. You really made it better. I have noticed that, it went s much smoother and cells stopped bouncing. Amazing job man! You will make Ogar successful!!

Do you KNOW how to adjust the splitting?

**Comment by Tiberiu02** [comment]
Thanks !
And what do you mean with adjust splitting ?

**Comment by NatsuTheGreat** [comment]
Well, I meant like make the splitting like originals agar.io's, not what it is now in Ogar, DO you know how both of those are very different

**Comment by Tiberiu02** [comment]
No

**Comment by NatsuTheGreat** [comment]
Oh alright. What about making collision for ejected mass?

**Pull request closed without merging**
